// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbioOsVPvXKt-Hs1P7SbaH0q25aU9ZEUM',
    appId: '1:331658418710:web:97c3314f3ae6710421b337',
    messagingSenderId: '331658418710',
    projectId: 'flutter-base5b',
    authDomain: 'flutter-base5b.firebaseapp.com',
    storageBucket: 'flutter-base5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_XT5QC_T2pUU30SMWIvSXBG_wP79fMrs',
    appId: '1:331658418710:android:70e3b90f03c9438321b337',
    messagingSenderId: '331658418710',
    projectId: 'flutter-base5b',
    storageBucket: 'flutter-base5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtyQ564IjG2X7HO-TlReeWLQbWicryUwA',
    appId: '1:331658418710:ios:7dff07782f0039ef21b337',
    messagingSenderId: '331658418710',
    projectId: 'flutter-base5b',
    storageBucket: 'flutter-base5b.firebasestorage.app',
    iosBundleId: 'com.ltorres.appfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtyQ564IjG2X7HO-TlReeWLQbWicryUwA',
    appId: '1:331658418710:ios:7dff07782f0039ef21b337',
    messagingSenderId: '331658418710',
    projectId: 'flutter-base5b',
    storageBucket: 'flutter-base5b.firebasestorage.app',
    iosBundleId: 'com.ltorres.appfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbioOsVPvXKt-Hs1P7SbaH0q25aU9ZEUM',
    appId: '1:331658418710:web:f78d3ba141ed5f1121b337',
    messagingSenderId: '331658418710',
    projectId: 'flutter-base5b',
    authDomain: 'flutter-base5b.firebaseapp.com',
    storageBucket: 'flutter-base5b.firebasestorage.app',
  );
}
